spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbit
    password: rabbit
    
    #default values for exchange & routing-key
    template:
      exchange: memo.queue
      routing-key: memo.info
      receive-timeout: 3000
