version: "3.9"
services:
  mongo-reactive-test:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - spring-reactice
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=mongo
networks:
  spring-reactive:
